# Generated by Django 5.1.15 on 2026-09-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershipment',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting for Seller Dispatch'), ('PICKED_UP', 'Picked Up by Courier'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned / Disputed'), ('CANCELLED', 'Cancelled')], db_index=True, default='WAITING', max_length=20),
        ),
    ]
