# Generated by Django 5.1.15 on 2026-10-03 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_booklisting_area_booklisting_condition_needs_review_and_more'),
        ('messaging', '0002_conversation_confirmed_at_and_more'),
        ('orders', '0002_alter_ordershipment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=12)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('accepted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('RESERVED', 'Reserved'), ('PICKUP_AGREED', 'Pickup agreed'), ('AWAITING_CONFIRMATION', 'Awaiting confirmation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('DISPUTED', 'Disputed')], db_index=True, default='REQUESTED', max_length=24)),
                ('reservation_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pickup_place', models.CharField(blank=True, max_length=255)),
                ('pickup_instructions', models.TextField(blank=True)),
                ('pickup_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('seller_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('problem_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='listings.booklisting'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'listing'), name='unique_cart_listing'),
        ),
        migrations.AddField(
            model_name='marketplacenotification',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='marketplacenotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketplacereport',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='listings.booklisting'),
        ),
        migrations.AddField(
            model_name='marketplacereport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agreement', to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='listings.booklisting'),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='pickup_proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketplacereport',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='orders.purchaseagreement'),
        ),
        migrations.AddField(
            model_name='sellerreview',
            name='agreement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='seller_review', to='orders.purchaseagreement'),
        ),
        migrations.AddConstraint(
            model_name='purchaseagreement',
            constraint=models.CheckConstraint(condition=models.Q(('offered_price__gt', 0)), name='positive_offer'),
        ),
        migrations.AddConstraint(
            model_name='purchaseagreement',
            constraint=models.CheckConstraint(condition=models.Q(('accepted_price__isnull', True), ('accepted_price__gt', 0), _connector='OR'), name='positive_accepted_price'),
        ),
        migrations.AddConstraint(
            model_name='purchaseagreement',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['RESERVED', 'PICKUP_AGREED', 'AWAITING_CONFIRMATION', 'DISPUTED'])), fields=('listing',), name='one_live_pickup_per_copy'),
        ),
        migrations.AddConstraint(
            model_name='sellerreview',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='seller_review_rating_range'),
        ),
    ]
