# Generated by Django 5.1.15 on 2026-10-03 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversation_confirmed_at_and_more'),
        ('orders', '0003_marketplacenotification_marketplacereport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseagreement',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='messaging.conversation'),
        ),
    ]
