# Generated by Django 5.1.15 on 2026-10-03 11:25

import apps.orders.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversation_confirmed_at_and_more'),
        ('orders', '0005_purchaseagreement_pickup_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacenotification',
            name='delivery_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketplacenotification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacenotification',
            name='last_delivery_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='marketplacenotification',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacereport',
            name='evidence',
            field=models.FileField(blank=True, storage=apps.orders.storage.PrivateEvidenceStorage(), upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='marketplacereport',
            name='reported_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_marketplace_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='offer_proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposed_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerreview',
            name='condition_accuracy_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerreview',
            name='punctuality_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketplacenotification',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.conversation'),
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='orders.marketplacereport')),
            ],
        ),
    ]
