# Generated by Django 5.1.15 on 2026-09-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='confirmed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Agreed/confirmed price at the time of seller approval', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='order_status',
            field=models.CharField(choices=[('INQUIRY', 'Awaiting Seller Confirmation'), ('CONFIRMED', 'Order Confirmed by Seller'), ('DECLINED', 'Order Declined'), ('COMPLETED', 'Purchased')], default='INQUIRY', help_text='Current state of order confirmation between buyer and seller', max_length=20),
        ),
    ]
