# Generated by Django 5.1.15 on 2026-09-13 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('seller_net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('HELD', 'Funds Held in Escrow'), ('RELEASED', 'Released to Seller Available Balance'), ('REFUNDED', 'Refunded to Buyer'), ('DISPUTED', 'Under Dispute')], db_index=True, default='HELD', max_length=15)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_holds', to='orders.order')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='orders.ordershipment')),
            ],
            options={
                'verbose_name': 'Escrow Hold',
                'verbose_name_plural': 'Escrow Holds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('SSLCOMMERZ', 'SSLCommerz'), ('STRIPE', 'Stripe'), ('BKASH', 'bKash Direct')], default='SSLCOMMERZ', max_length=20)),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Payment Successful'), ('FAILED', 'Payment Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='INITIATED', max_length=15)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_method', models.CharField(max_length=20)),
                ('account_details', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payout Batch',
                'verbose_name_plural': 'Payout Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('SALE_CREDIT', 'Sale Revenue'), ('PLATFORM_FEE', 'Platform Commission'), ('PAYOUT_DEBIT', 'Bank/MFS Withdrawal'), ('REFUND_DEBIT', 'Order Refund')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_id', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Ledger',
                'verbose_name_plural': 'Seller Ledgers',
                'ordering': ['-created_at'],
            },
        ),
    ]
