# Generated by Django 5.1.15 on 2026-09-13 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('LIKE_NEW', 'Like New (Minimal signs of wear)'), ('VERY_GOOD', 'Very Good (Clean pages, light spine creasing)'), ('GOOD', 'Good (Average used wear, possible notes/highlights)'), ('ACCEPTABLE', 'Acceptable (Readable copy, noticeable wear or damage)'), ('COLLECTIBLE', 'Collectible / Vintage (Rare edition, signed)')], db_index=True, default='GOOD', max_length=20)),
                ('condition_notes', models.TextField(blank=True, help_text='Specific wear details: markings, tears, yellowed pages, bindings.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Listing price in platform currency.', max_digits=8)),
                ('original_mrp', models.DecimalField(blank=True, decimal_places=2, help_text='Original printed cover price (for comparison).', max_digits=8, null=True)),
                ('edition_year', models.PositiveIntegerField(blank=True, help_text='Year this specific physical copy was printed.', null=True)),
                ('is_hardcover', models.BooleanField(default=False)),
                ('has_dust_jacket', models.BooleanField(default=False)),
                ('is_signed_by_author', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active / Available'), ('RESERVED', 'Reserved (Checkout in progress)'), ('SOLD', 'Sold'), ('ARCHIVED', 'Archived / Deactivated')], db_index=True, default='ACTIVE', max_length=15)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(help_text='The canonical book record.', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='books.book')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book Listing',
                'verbose_name_plural': 'Book Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_photos/%Y/%m/')),
                ('webp_image', models.ImageField(blank=True, null=True, upload_to='listing_photos/webp/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.booklisting')),
            ],
            options={
                'verbose_name': 'Listing Image',
                'verbose_name_plural': 'Listing Images',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booklisting',
            index=models.Index(fields=['status', 'condition', 'price'], name='listings_bo_status_9d597b_idx'),
        ),
        migrations.AddIndex(
            model_name='booklisting',
            index=models.Index(fields=['seller', 'status'], name='listings_bo_seller__ffc67f_idx'),
        ),
    ]
