# Generated by Django 5.1.15 on 2026-10-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklisting',
            name='area',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booklisting',
            name='condition_needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booklisting',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booklisting',
            name='is_collectible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booklisting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='booklisting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='booklisting',
            name='condition',
            field=models.CharField(choices=[('LIKE_NEW', 'Like New (Minimal signs of wear)'), ('VERY_GOOD', 'Very Good (Clean pages, light spine creasing)'), ('GOOD', 'Good (Average used wear, possible notes/highlights)'), ('ACCEPTABLE', 'Acceptable (Readable copy, noticeable wear or damage)'), ('POOR', 'Poor (Heavy wear; describe defects)')], db_index=True, default='GOOD', max_length=20),
        ),
    ]
