# Generated by Django 5.1.15 on 2026-10-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_preserve_collectible_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklisting',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active / Available'), ('RESERVED', 'Reserved (Awaiting pickup)'), ('SOLD', 'Sold'), ('ARCHIVED', 'Archived / Deactivated')], db_index=True, default='ACTIVE', max_length=15),
        ),
    ]
